### ISSUE TITLE
Create /questionanswering service interface 

### ISSUE THREAD

**Issue by anbo-de** [WDAqua/Qanary#12]
Goal: easy configuration of a Question Answering process, enable RESTful interface driven configuration of a Question Answering process.
 * enable parameters to configure the Question Answering process run:
   * language (of question)
   * targetdata (knowledge base that should be used to compute the answer)
 * implement GET, POST, PUT, DELETE

Branch: callsToBackend

**Comment by D063520** [comment]
refactored interface /startquestionansweringwithtextquestion
refactored interface /startquestionansweringwithtextquestion

created new interface /questionansweringfull

commits 
ebf835f54498c08db8f187bc9686305519fb3682
d4cbe97c66ae4d537a8563e070e5f826aa113753
