### ISSUE TITLE
Partial Names

### ISSUE THREAD

**Issue by RicardoUsbeck** [WDAqua/Qanary#13]
Hi, 

we tested your great service with some users. They tend to use partial names, such as "Tell me about Obama" and then expect the most popular result. Unfortunately, the ranking breaks them. Is there a solution for that.  (Reporting for @ram-g-athreya)

Cheers
Ricarsdo

**Comment by D063520** [comment]
Hi Ricardo,
can you describe a bit more the problem? I have seen that "Tell me about obama" does not work. Do you want to say the query is generated but not ranked correctly? It is also a bit a matter of training.
Salut
Dennis

**Comment by ram-g-athreya** [comment]
Hi @D063520 would it be possible to recognize partial names such as obama => [Barack Obama](http://dbpedia.org/resource/Barack_Obama), i.e the most likely entity so that we can show relevant results back to the users?

**Comment by D063520** [comment]
Hi ram-g-athreya,

in fact we are already doing something like this. For example:

https://wdaqua-frontend.univ-st-etienne.fr/question?query=Obama&lang=en&kb=wikidata

https://wdaqua-frontend.univ-st-etienne.fr/question?query=Obama&lang=en&kb=dbpedia

What is going wrong is the "Tell me about". We can probably train the QA system to recognise such types of questions. We did not encounter them before.

Salut
D063520

**Comment by D063520** [comment]
Hi, I have now fixed it for the question you told me. Give a look:

https://wdaqua-frontend.univ-st-etienne.fr/question?query=Tell%20me%20about%20obama&lang=en&kb=wikidata

**Comment by ram-g-athreya** [comment]
Hi @D063520 

Its working better now.

Thanks
Ram G Athreya
