### ISSUE TITLE
Wiki about additional triples should state the needed version

### ISSUE THREAD

**Issue by fredericbahr** [WDAqua/Qanary#143]
The wiki entry "Inject additional information to a Qanary process" should in my opinion state as a requirement that the docker-version 3.7.0 is needed as the feature (as far as i understand) was released 5 days ago with the currently latest [MR](https://github.com/WDAqua/Qanary/commit/aa5437345b449421dcf0740e07e4325d47cf0b70)

I tested the `additionalTriples` property with the version 3.5.1 and was wondering why this feature was not working.

Adding the requirements in the wiki can save other developers from making the same mistake and states that this feature is only available with version 3.7.0+

**Comment by anbo-de** [comment]
@fredericbahr You are correct, the tutorial is only working in Qanary pipeline v3.7.0+. Earlier versions support a different behavior, which was improved in v3.7.0. I added a remark to https://github.com/WDAqua/Qanary/wiki/Inject-additional-information-to-a-Qanary-process.
