### ISSUE TITLE
Loglevel via environment variable

### ISSUE THREAD

**Issue by fredericbahr** [WDAqua/Qanary#145]
When the Qanary pipeline is started locally as a Docker service, it logs a lot of information.

These logs are usually very helpful, however it can happen that it logs too much  so that (at least my CLI) doesn't show previous logs.

Likewise, logs from custom Qanary components can be overlooked very easily aswell.

Therefore I would appreciate it, if one could define the log level by an environment variable in the `docker-compose.yml`.

If this is already possible, I would appreciate a code snippet.

**Comment by anbo-de** [comment]
Hi @fredericbahr.

@Perevalov Was already describing on how to reduce the logs you see while using `docker-compose`. 

If you want to reduce the entries written to the log by the application, you need to use a different approach. Qanary provides the same configuration options as other applications driven by Java / Spring Boot based or Docker. Now, I wrote a wiki page about the behavior that you can find [here](https://github.com/WDAqua/Qanary/wiki/Set-environment-variables-for-your-application).

In your particular case, setting the following parameters might already help (just add additional parameters for the packages where you want to restrict the logging):

```
java -Dlogging.level.eu.wdaqua.qanary=WARN \
     -Dlogging.level.=WARN \
     -Dlogging.level.org.springframework.security=WARN
     -Dlogging.level.eu.wdaqua.qanary=WARN \
...
```

Here, the statement is dedicated to starting the JAR file. In other case, see the aforementioned wiki page on how to set the parameters.

Hope it helps.
