### ISSUE TITLE
Provide Docker containers for all Qanary components

### ISSUE THREAD

**Issue by anbo-de** [WDAqua/Qanary#2]
Definition of Done:
- a standardized process is defined for creating Docker for the components written in Java
- for each Qanary service component and the Qanary pipeline a Docker container is provided, tested and available
- a compact but solid documentation is available in the [Github wiki](https://github.com/WDAqua/Qanary/wiki) covering the process to create a Docker container for a new component

**Comment by RicardoUsbeck** [comment]
It would be good to have a docker-compose file to just run three commands to be up an running. 

$ git clone
$ cd Qanary/
$ docker-compose up

What do you think?

**Comment by ilytra** [comment]
docker-compose would be a nice idea if we would have some fix services that run only at a specific server. At the moment the idea is that we have a microservices architecture where the components are distributed. At the moment we have a script to start the containers (i.e., start.sh). In the future, we can consider using docker-compose.

**Comment by RicardoUsbeck** [comment]
Thanks for your answer, now I am running into a new problem

```
Ricardos-MBP:Qanary ricardousbeck$ ./start.sh 
00a1c450e176
c5d1b0139cde
9552510b98dd
d88863d2656d
063e015ca5e4
00a1c450e176
c5d1b0139cde
9552510b98dd
d88863d2656d
063e015ca5e4
Starting stardog container
Unable to find image 'qanary/stardog:latest' locally
Pulling repository docker.io/qanary/stardog
docker: Error: image qanary/stardog not found.
See 'docker run --help'.
Starting qapipeline container
Unable to find image 'qanary/qapipeline:latest' locally
Pulling repository docker.io/qanary/qapipeline
docker: Error: image qanary/qapipeline not found.
See 'docker run --help'.
Starting agdistis-ned component container
Unable to find image 'qanary/agdistis-ned:latest' locally
Pulling repository docker.io/qanary/agdistis-ned
docker: Error: image qanary/agdistis-ned not found.
See 'docker run --help'.
```
With the docker 
```
Ricardos-MBP:Qanary ricardousbeck$ docker -v
Docker version 1.11.0, build 4dc5990```

**Comment by ilytra** [comment]
have a look at the updated documentation here https://github.com/WDAqua/Qanary. You need to execute `mvn clean install`at the project root folder, this also generates the docker images. I will add a ticket for sending the images to docker hub. There is also the option to start Qanary without docker. Regarding stardog have a look here: https://github.com/WDAqua/Qanary/tree/master/stardog - we cannot provide an image for stardog, as it is proprietary.

**Comment by RicardoUsbeck** [comment]
Thanks for the quick reply!
After `mvn clean package install -DskipTests` it started working. 
My build fails however. Does the build really take that long?
![image](https://cloud.githubusercontent.com/assets/4354740/17550540/bbbcbbf8-5ef5-11e6-8770-b8a283a86902.png)

**Comment by ilytra** [comment]
This was because of a typo in the Dockerfile. I fixed it quickly. Yes it takes a lot of time because it creates the docker images. But you can run the project without docker as well: `mvn clean install -DskipDockerBuild`
