### ISSUE TITLE
Install Qanary using docker

### ISSUE THREAD

**Issue by mateusccoelho** [WDAqua/Qanary#20]
Hi, I'm trying to install Qanary with docker following the readme instructions. But I couldn't find any documentation about start.sh and initdb.sh scripts. I searched in Wiki and the source code but couldn't find anything. 

Where do I get these scripts or configure them?

**Comment by jannlemm0913** [comment]
Hello, I think I found the scripts in the Frankenstein repository. Frankenstein is a related project that also uses Qanary components. In [this repository](https://github.com/WDAqua/Frankenstein/tree/master/Qanary) you can find both the start.sh and the initdb.sh scripts. I don't know why they are not on this repo.

**Comment by mateusccoelho** [comment]
Thanks for your reply @jannlemm0913.

I got the scripts there but faced some other problems along the way to build Qanary. So, just in case someone reads this, I gonna tell how I managed to make it work using docker.

I started following the tutorial in the README and installed the core components of Qanary, which are in this repo. Then I cloned the repo Qanary-question-answering-components and using mvn clean install I installed all QA components. In this part I faced two problems:

1. When we install a component, first a JAR is generated with the name and version contained in the pom file. Then a Dockerfile generates the docker image using this JAR. However, in the Dockerfile, the JAR name is hardcoded and in some components it differed from the actual JAR name generated. So I just had to change the JAR name in the dockerfile to reflect the new name or new version contained in the pom.xml.

2. In each component, the dockerfile must in be in the root of the folder docker. But in some of them, it wasn't, so I had to move it to the root.

Also, there are two thing that weren't in the tutorial. First is that you need to rename each component docker image name in the pom.xml. Also, for some reason, it must not contain any upper case letters. The second thing is that you need to build a stardog docker image. To do so, head to the repo Frankstein and inside the Qanary folder, there is a folder called stardog. In it you can find a README.md with instructions. 

That's it to build Qanary.

**Comment by anbo-de** [comment]
@mateusccoelho Thanks for sharing your experience.
