### ISSUE TITLE
Using Qanary on Windows

### ISSUE THREAD

**Issue by p-Heinze** [WDAqua/Qanary#21]
@anbo-de 
I'm having difficulties using Qanary on Windows
There seems to be a hard coded directory 'tmp/questions' for question data in QanaryQuestionController.java

**Comment by anbo-de** [comment]
Thanks for the note. We will add a configurable path value, soon.

**Comment by anbo-de** [comment]
Solved in Qanary Pipeline version 2.1.2, see commit https://github.com/WDAqua/Qanary/commit/4590a2e236274dadefabd71637b1956c06e61556. 

Please report if Qanary is now working on your Windows machine.

**Comment by anbo-de** [comment]
Works on Windows, now.
