### ISSUE TITLE
How to make a component register itself? 

### ISSUE THREAD

**Issue by rrichajalota** [WDAqua/Qanary#32]
Hello, 

I am trying to run the QANARY framework with the existing components - qa.NED-DBpedia-Spotlight and qanary_component-QB-SimpleRealNameOfSuperHero, [as mentioned](https://github.com/WDAqua/Qanary/wiki/Configuration-Parameters-of-a-Qanary-Pipeline) in the [readme](https://github.com/WDAqua/Qanary-question-answering-components). However, I get the following warning about the components failing to register themselves: <br />
`2020-08-20 12:31:25.780  WARN 20737 --- [gistrationTask1] d.c.b.a.c.r.ApplicationRegistrator       : Failed to register application as Application(name=NED-DBpediaSpotlight, managementUrl=http://localhost:10008/actuator, healthUrl=http://localhost:10008/actuator/health, serviceUrl=http://localhost:10008/) at spring-boot-admin ([http://localhost:8080/instances]): I/O error on POST request for "http://localhost:8080/instances": Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused); nested exception is org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused). Further attempts are logged on DEBUG level
`  <br />
Consequently, I believe, the endpoint http://localhost:8080/startquestionansweringwithtextquestion is not able to give an answer to any question. Could you please help me in setting up the components in the pipeline? What am I missing?

**Comment by rrichajalota** [comment]
Hey @anbo-de, I was able to resolve the above issue by restarting stardog. In the interactive mode, the QA pipeline seems to work now but I am not able to retrieve the SPARQL query from the question analysis outgraph. It returns "unauthorized access" every time. 
![Screenshot from 2020-08-25 15-35-30](https://user-images.githubusercontent.com/13457022/91181547-5e2d0a80-e6e9-11ea-9e00-9504a2c78af0.png)

**Comment by anbo-de** [comment]
@rrichajalota Is it possible to open the URL of your Stardog endpoint in the browser? Given your screenshot please try both used endpoints: 
 * http://localhost:5820/qanary
 * http://127.0.0.1:5820/qanary
Maybe only one is working. 

Additionally, please check the Web developer console of your Web browser for the complete error message and report it here.

**Comment by anbo-de** [comment]
No new feedback for 4 weeks. Hence, I assume the problem was solved.
