### ISSUE TITLE
Error while building new component (java: cannot find symbol QanaryComponentConfiguration)

### ISSUE THREAD

**Issue by Perevalov** [WDAqua/Qanary#33]
I'm trying to implement a new Qanary component according to the instruction https://github.com/WDAqua/Qanary/wiki/How-do-I-integrate-a-new-component-in-Qanary%3F. However, on Step 3, while executing `mvn clean install` inside of the component folder I get following output:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/alex/Qanary-dev/Qanary/qanary_component_answer-type-classifier/src/main/java/eu/wdaqua/qanary/answertypeclassifier/Application.java:[10,34] cannot find symbol
  symbol:   class QanaryComponentConfiguration
  location: package eu.wdaqua.qanary.component
[ERROR] /home/alex/Qanary-dev/Qanary/qanary_component_answer-type-classifier/src/main/java/eu/wdaqua/qanary/answertypeclassifier/Application.java:[34,16] cannot find symbol
  symbol:   class QanaryComponentConfiguration
  location: class eu.wdaqua.qanary.answertypeclassifier.Application
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.273 s
[INFO] Finished at: 2020-09-08T15:45:58+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project qanary_component_answer-type-classifier: Compilation failure: Compilation failure: 
[ERROR] /home/alex/Qanary-dev/Qanary/qanary_component_answer-type-classifier/src/main/java/eu/wdaqua/qanary/answertypeclassifier/Application.java:[10,34] cannot find symbol
[ERROR]   symbol:   class QanaryComponentConfiguration
[ERROR]   location: package eu.wdaqua.qanary.component
[ERROR] /home/alex/Qanary-dev/Qanary/qanary_component_answer-type-classifier/src/main/java/eu/wdaqua/qanary/answertypeclassifier/Application.java:[34,16] cannot find symbol
[ERROR]   symbol:   class QanaryComponentConfiguration
[ERROR]   location: class eu.wdaqua.qanary.answertypeclassifier.Application
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Steps to reproduce:

1. Clone https://github.com/WDAqua/Qanary
2. Run `mvn install` inside Qanary folder
3. Run ` mvn archetype:generate` with custom settings (See step 2 of the instruction)
4. Implement functionality (no errors)
5. Run `mvn clean install`

**Comment by anbo-de** [comment]
Problem was caused by a faulty Maven installation.

**Comment by sukannyapurkayastha** [comment]
Getting this error on installation: 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project qa.pipeline: Fatal error compiling: invalid flag: --release -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :qa.pipeline

**Comment by anbo-de** [comment]
@sukannyapurkayastha It looks like a problem with the Maven installation. What Maven version is running on your system?

Have you tried:
* deleting the directory `.m2/repository`?
* running `mvn clean install -X`?
