### ISSUE TITLE
Push Qanary docker images to Docker Hub

### ISSUE THREAD

**Issue by ilytra** [WDAqua/Qanary#7]
- Use Docker Hub repository (https://hub.docker.com/) for sharing the Qanary docker images.
- The docker images should be pushed to Docker Hub whenever changes are pushed to Qanary master.

**Comment by p-Heinze** [comment]
Thank you for this suggestion.

The newest version of the Qanary pipeline docker image is available as `qanary/qanary-pipeline:2.2.0` on Docker Hub. 
There you can also find a web front end for on-the-fly configuration of the pipeline (`qanary/qanary-configuration-frontend:1.0.1`).

**Comment by anbo-de** [comment]
Thanks to @p-Heinze the Qanary-related Docker Images are available. Please see https://hub.docker.com/search?q=qanary&type=image for a list.
